### ISSUE TITLE
impacting package that only support 8.2 in a package test

### ISSUE THREAD

**Issue by pemudakoding** [spatie/php-cloneable#7]
Hi.

I hope the contributor's and the owners is good in health and have a nice day. 
So I've package that only support php 8.2 but it not a main problem here, So in our package we consume cloneable to utilize the DTO, our DTO as default using readonly classes but we need support package with older version.

our package test using 2 version prefer stable and prefer lowest, and the prefer stable everything is fine, but when prefer lowest the test hit error cause the version 1.0.0 of php-cloneable isn't support any readonly class. it only happens in 1.0.1. 

so if whe need go fordward we need to give up in prefer lowest test. but before we do that, is this package has any solution to make any package that consume this package still smooth of support older version?
but from me I think it more make sense if we treat #6  as minor release (adding new feature) instead of patch release (fix bug).
so with that solution probably able to let us using 2 test in our package 

Thanks

**Comment by rubenvanassche** [comment]
I don't think we can untag a release, so I'm afraid we cannot provide a solution here.
